from .Add import Add
from .Addi import Addi
from .Beq import Beq
from .Bge import Bge
from .Bgt import Bgt
from .Blank import Blank
from .Ble import Ble
from .Blt import Blt
from .Bne import Bne
from .Div import Div
from .FAdd import FAdd
from .FDiv import FDiv
from .FImm import FImm
from .FMul import FMul
from .FMv import FMv
from .FNeg import FNeg
from .FSub import FSub
from .Feq import Feq
from .Fle import Fle
from .Flt import Flt
from .Flw import Flw
from .Fsw import Fsw
from .GetF import GetF
from .GetI import GetI
from .Halt import Halt
from .Instruction3O import Instruction3O
from .InstructionBranch import InstructionBranch
from .InstructionLS import InstructionLS
from .InstructionPut import InstructionPut
from .Instruction import Instruction
from .J import J
from .Jr import Jr
from .La import La
from .Label import Label
from .Li import Li
from .Lw import Lw
from .Mul import Mul
from .Mv import Mv
from .Neg import Neg
from .PopFloat import PopFloat
from .PopInt import PopInt
from .PushFloat import PushFloat
from .PushInt import PushInt
from .PutF import PutF
from .PutI import PutI
from .PutS import PutS
from .Ret import Ret
from .Sub import Sub
from .Sw import Sw
